@CachedInventory_HostAddress = http://localhost:5250
@ProductId = 4

GET {{CachedInventory_HostAddress}}/stock/{{ProductId}} HTTP/2
Accept: application/json

####

POST {{CachedInventory_HostAddress}}/stock/retrieve HTTP/2
Content-Type: application/json

{
    "productId": {{ProductId}},
    "amount": 5
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

####

POST {{CachedInventory_HostAddress}}/stock/restock HTTP/2
Content-Type: application/json

{
    "productId": {{ProductId}},
    "amount": 5
}
